#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/roadstr

PRODUCT_COPY_FILES += \
    vendor/motorola/roadstr/proprietary/system_ext/bin/hw/motorola.hardware.tcmdaidl-service:$(TARGET_COPY_OUT_SYSTEM_EXT)/bin/hw/motorola.hardware.tcmdaidl-service \
    vendor/motorola/roadstr/proprietary/system_ext/etc/init/motorola.hardware.tcmd@1.0-service.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/motorola.hardware.tcmd@1.0-service.rc \
    vendor/motorola/roadstr/proprietary/system_ext/etc/init/motorola.hardware.tcmdaidl-service.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/motorola.hardware.tcmdaidl-service.rc \
    vendor/motorola/roadstr/proprietary/system_ext/etc/permissions/com.dolby.daxservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.dolby.daxservice.xml \
    vendor/motorola/roadstr/proprietary/system_ext/etc/permissions/com.motorola.hardware.display_refresh_rate_v3.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.motorola.hardware.display_refresh_rate_v3.xml \
    vendor/motorola/roadstr/proprietary/system_ext/lib64/libmmiipstreammmihttp.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libmmiipstreammmihttp.so \
    vendor/motorola/roadstr/proprietary/system_ext/lib64/libmmipstreamnetwork.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libmmipstreamnetwork.so \
    vendor/motorola/roadstr/proprietary/system_ext/lib64/libmmipstreamsourcehttp.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libmmipstreamsourcehttp.so \
    vendor/motorola/roadstr/proprietary/system_ext/lib64/libmmipstreamutils.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libmmipstreamutils.so \
    vendor/motorola/roadstr/proprietary/system_ext/lib64/motorola.hardware.camera.desktop@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/motorola.hardware.camera.desktop@1.0.so \
    vendor/motorola/roadstr/proprietary/system_ext/lib64/motorola.hardware.camera.desktop@2.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/motorola.hardware.camera.desktop@2.0.so \
    vendor/motorola/roadstr/proprietary/system_ext/lib64/motorola.hardware.tcmd@1.0.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/motorola.hardware.tcmd@1.0.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoft_aec_luma_calc_bm.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoft_aec_luma_calc_bm.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoft_aec_luma_calculation.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoft_aec_luma_calculation.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoft_calibverify_TriCamera.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoft_calibverify_TriCamera.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoft_calibverify_TriCamera_ctwo.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoft_calibverify_TriCamera_ctwo.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoft_distortion_calibration.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoft_distortion_calibration.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoft_tricam_calibration.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoft_tricam_calibration.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoft_tricam_calibration_ctwo.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoft_tricam_calibration_ctwo.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoft_tricam_verification.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoft_tricam_verification.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoft_tricam_verification_ctwo.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoft_tricam_verification_ctwo.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoftbase.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoftbase.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoftcalibration_ctwo_jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoftcalibration_ctwo_jni.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoftcalibration_jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoftcalibration_jni.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoftdistortion_jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoftdistortion_jni.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoftdistortionvf_jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoftdistortionvf_jni.so \
    vendor/motorola/roadstr/proprietary/system_ext/priv-app/CQATest/lib/arm64/libarcsoftverification_jni.so:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/CQATest/lib/arm64/libarcsoftverification_jni.so \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/android.hardware.biometrics.fingerprint@2.1-goodixservice:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.biometrics.fingerprint@2.1-goodixservice \
    vendor/motorola/roadstr/proprietary/vendor/etc/HapticsPolicy.xml:$(TARGET_COPY_OUT_VENDOR)/etc/HapticsPolicy.xml \
    vendor/motorola/roadstr/proprietary/vendor/etc/Hapticsconfig.xml:$(TARGET_COPY_OUT_VENDOR)/etc/Hapticsconfig.xml \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/ffv_models/fai__4.8.14_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.11.0_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/fai__4.8.14_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.11.0_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/ffv_models/ffv__5.0.2_0.1__eai_4.8_enpu_v5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__5.0.2_0.1__eai_4.8_enpu_v5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/ffv_models/ffv__7.1.1_0.1__eai_4.8_enpu_v5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__7.1.1_0.1__eai_4.8_enpu_v5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/ffv_models/ffv__7.1.1_0.2__eai_4.8_enpu_v5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/ffv__7.1.1_0.2__eai_4.8_enpu_v5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/ffv_models/hk01b_relu_eAI_4.6_eNPU_V5_adsp_i.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ffv_models/hk01b_relu_eAI_4.6_eNPU_V5_adsp_i.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/click.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/click.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/double_click.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/double_click.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/heavy_click.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/heavy_click.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/pop.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/pop.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/reserved_1.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_1.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/reserved_2.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_2.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/reserved_3.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_3.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/reserved_4.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_4.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/reserved_5.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_5.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/reserved_6.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_6.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/reserved_7.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_7.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/reserved_8.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/reserved_8.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/texture_tick.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/texture_tick.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/thud.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/thud.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/haptics_data/tick.pcm:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/haptics_data/tick.pcm \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/kera_qrd/QRD_kera_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kera_qrd/QRD_kera_acdb_cal.acdb \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/kera_qrd/QRD_kera_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kera_qrd/QRD_kera_workspaceFileXml.qwsp \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/kera_qrd/speaker_lc/QRD_kera_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kera_qrd/speaker_lc/QRD_kera_acdb_cal.acdb \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/kera_qrd/speaker_lc/QRD_kera_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kera_qrd/speaker_lc/QRD_kera_workspaceFileXml.qwsp \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.7_enpu3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.7_enpu3.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.36_enpu2_comp.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.3_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.6.5_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.2_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.2_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.2_0.0__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.5_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.6_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.6_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.7_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.7_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.8_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.2_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.2_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.0_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.0__eai_3.4_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.2_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.2_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.9.2_1.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.2_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.2_0.0__3.0.0_0.0__3.1.1.0_0.0__3.2.0_0.0__eai_2.7_enpu_v3.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.3_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.3_0.0__3.0.0_0.0__3.1.0_0.0__3.2.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.0_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.2_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.2_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__4.8.4_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.1_0.0__3.2.0_0.1__eai_3.4_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.2_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.2_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__8.0.2_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__8.0.3_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__8.0.3_0.0__3.0.0_0.0__3.1.2_0.0__3.2.0_0.1__eai_4.6_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.36_enpu2.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.36_enpu2.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_2.10_enpuv3.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_2.10_enpuv3.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_3.4_enpuv4.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_3.4_enpuv4.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_4.2_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_4.2_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_4.6_enpuv5.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_4.6_enpuv5.pmd \
    vendor/motorola/roadstr/proprietary/vendor/etc/camera/arcsoft_calibration_u_dc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/arcsoft_calibration_u_dc.bin \
    vendor/motorola/roadstr/proprietary/vendor/etc/camera/mot_engine_config.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mot_engine_config.bin \
    vendor/motorola/roadstr/proprietary/vendor/etc/camera/vidhance.lic:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance.lic \
    vendor/motorola/roadstr/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/motorola/roadstr/proprietary/vendor/etc/display/qdcm_calib_data_Sharp_qhd_cmd_mode_dsi_panel.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_Sharp_qhd_cmd_mode_dsi_panel.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/display/qdcm_calib_data_Sharp_qhd_video_mode_dsi_panel.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_Sharp_qhd_video_mode_dsi_panel.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/display/qdcm_calib_data_mipi_mot_vid_boe_nt37706_1220p_dsc_667.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_mipi_mot_vid_boe_nt37706_1220p_dsc_667.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/display/qdcm_calib_data_mipi_mot_vid_csot_1220p_dsc_667.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_mipi_mot_vid_csot_1220p_dsc_667.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/display/qdcm_calib_data_mipi_mot_vid_csot_nt37706_1220p_dsc_667.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_mipi_mot_vid_csot_nt37706_1220p_dsc_667.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/display/qdcm_calib_data_mipi_mot_video_dummy_qhd.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_mipi_mot_video_dummy_qhd.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/display/qdcm_calib_data_vtdr6130_amoled_cmd_mode_dsi_visionox_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_vtdr6130_amoled_cmd_mode_dsi_visionox_panel_with_DSC.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/display/qdcm_calib_data_vtdr6130_amoled_qsync_cmd_mode_dsi_visionox_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_vtdr6130_amoled_qsync_cmd_mode_dsi_visionox_panel_with_DSC.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/display/qdcm_calib_data_vtdr6130_amoled_qsync_video_mode_dsi_visionox_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_vtdr6130_amoled_qsync_video_mode_dsi_visionox_panel_with_DSC.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/display/qdcm_calib_data_vtdr6130_amoled_video_mode_dsi_visionox_panel_with_DSC.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_vtdr6130_amoled_video_mode_dsi_visionox_panel_with_DSC.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/dolby/dax-default-spatializer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default-spatializer.xml \
    vendor/motorola/roadstr/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/motorola/roadstr/proprietary/vendor/etc/dolby/dax-moto_1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-moto_1.xml \
    vendor/motorola/roadstr/proprietary/vendor/etc/dolby/dax-moto_2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-moto_2.xml \
    vendor/motorola/roadstr/proprietary/vendor/etc/dolby/dax-moto_3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-moto_3.xml \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint-service-jv2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint-service-jv2.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/com.motorola.hardware.display.panel-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.motorola.hardware.display.panel-service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/com.motorola.hardware.display.touch-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.motorola.hardware.display.touch-service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/com.motorola.hardware.ifaa-V1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/com.motorola.hardware.ifaa-V1-service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/fingerprint-goodix.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fingerprint-goodix.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/hw/init.vendor.st21nfc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.vendor.st21nfc.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/motorola.hardware.fdr.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.fdr.service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/motorola.hardware.haptic-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.haptic-service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/motorola.hardware.health.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.health.service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/motorola.hardware.health.storage.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.health.storage.service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/motorola.hardware.health.storage@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.health.storage@1.0-service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/motorola.hardware.lpsensing.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.lpsensing.service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/motorola.hardware.power.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.power.service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/motorola.hardware.rpmb.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.rpmb.service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/motorola.hardware.sensorext.service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.sensorext.service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/motorola.hardware.wireless.wlc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/motorola.hardware.wireless.wlc-service.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/init/vendor.dolby.media.c2-default-service-dax.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.media.c2-default-service-dax.rc \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-SN220_19_2MHZ.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-SN220_19_2MHZ.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-SN220_38_4MHZ.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-SN220_38_4MHZ.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-SN300_38_4MHZ.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-SN300_38_4MHZ.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-hal-st-felica.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st-felica.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-hal-st-prc.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st-prc.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-hal-st-uicc.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st-uicc.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-hal-st.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-mtp-SN100.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp-SN100.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-mtp-SN100_38_4MHZ.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-mtp-SN100_38_4MHZ.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-nci-st-felica.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci-st-felica.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-nci-st.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci-st.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-qrd-SN100.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd-SN100.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/libnfc-qrd-SN100_38_4MHZ.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-qrd-SN100_38_4MHZ.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/bonito_qsh_ble_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_qsh_ble_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/eliza_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_bu52053nvx_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/eliza_ccd_base.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_ccd_base.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/eliza_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_default_sensors.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/eliza_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_dynamic_sensors.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/eliza_dynamic_sensors_template.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_dynamic_sensors_template.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/eliza_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_irq.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/eliza_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_power_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/eliza_qrd_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_qrd_default_sensors.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/eliza_qsh_ble_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_qsh_ble_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/eliza_sht4x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_sht4x_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/icm456xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icm456xx_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/json.lst:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/json.lst \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mmc56x3x_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/mmc56x3x_0_evt_always.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mmc56x3x_0_evt_always.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/mot_camgest.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_camgest.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/mot_chopchop.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_chopchop.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/mot_ftm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_ftm.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/mot_ltv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_ltv.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/mot_stowed.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_stowed.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/mot_tap.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_tap.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/mot_vsync_psd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_vsync_psd.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/pakala_qsh_ble_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_qsh_ble_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/qmc630x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qmc630x_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/qsh_ble.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_ble.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/qsh_camera_common.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_common.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/qsh_camera_common_sm8735.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_common_sm8735.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_6.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_6.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/qsh_camera_imx688_6_actuator.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_imx688_6_actuator.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/qsh_camera_ov32c4c_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_ov32c4c_4.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/qsh_camera_ov32c4c_4_sm8735.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_ov32c4c_4_sm8735.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_amd.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_ttw.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_ttw.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v2_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_0_walk.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v3_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_0_walk.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_sensors.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v5_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v5_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v5_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v5_0_te_cd_regs.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v5_1_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v5_1_te_cd_regs.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v6_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v6_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v6_0_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v6_0_sensors.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_ccd_v6_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v6_0_te_cd_regs.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_flight_md.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_flight_md.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_offbody_detect_phone.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_offbody_detect_phone.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_psd_disable.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_psd_disable.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_psd_enable.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_psd_enable.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_transport_ppe.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_transport_ppe.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/stk3bfx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/stk3bfx_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/stk3bfx_0_boe_always.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/stk3bfx_0_boe_always.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/stk3bfx_0_csot_always.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/stk3bfx_0_csot_always.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/sensors/config/stk6b9x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/stk6b9x_0.json \
    vendor/motorola/roadstr/proprietary/vendor/etc/st21nfc_conf_ds.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st21nfc_conf_ds.txt \
    vendor/motorola/roadstr/proprietary/vendor/etc/st21nfc_conf_ss.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st21nfc_conf_ss.txt \
    vendor/motorola/roadstr/proprietary/vendor/etc/st54l_conf_ds.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st54l_conf_ds.txt \
    vendor/motorola/roadstr/proprietary/vendor/etc/st54l_conf_felica_ds.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st54l_conf_felica_ds.txt \
    vendor/motorola/roadstr/proprietary/vendor/etc/st54l_conf_felica_ss.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st54l_conf_felica_ss.txt \
    vendor/motorola/roadstr/proprietary/vendor/etc/st54l_conf_ss.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st54l_conf_ss.txt \
    vendor/motorola/roadstr/proprietary/vendor/etc/thermal-engine-roadstr-aifastc.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-roadstr-aifastc.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/thermal-engine-roadstr-auto.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-roadstr-auto.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/thermal-engine-roadstr-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-roadstr-camera.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/thermal-engine-roadstr-fact.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-roadstr-fact.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/thermal-engine-roadstr-fastc.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-roadstr-fastc.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/thermal-engine-roadstr-game-perf.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-roadstr-game-perf.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/thermal-engine-roadstr-gb.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-roadstr-gb.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/thermal-engine-roadstr-perf.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-roadstr-perf.conf \
    vendor/motorola/roadstr/proprietary/vendor/etc/thermal-engine-roadstr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-roadstr.conf \
    vendor/motorola/roadstr/proprietary/vendor/firmware/csot_goodix_cfg_group.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/csot_goodix_cfg_group.bin \
    vendor/motorola/roadstr/proprietary/vendor/firmware/goodix-csot-gt9916P-25090505-68ba9153-roadstr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix-csot-gt9916P-25090505-68ba9153-roadstr.bin \
    vendor/motorola/roadstr/proprietary/vendor/firmware/st21nfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_fw.bin \
    vendor/motorola/roadstr/proprietary/vendor/firmware/st21nfc_fw7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_fw7.bin \
    vendor/motorola/roadstr/proprietary/vendor/firmware/st54l_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st54l_fw.bin \
    vendor/motorola/roadstr/proprietary/vendor/firmware/st54l_fw_felica.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st54l_fw_felica.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.mot.eeprom.mot_gt24p128g_s5kgnj_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.mot.eeprom.mot_gt24p128g_s5kgnj_eeprom.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.mot.eeprom.mot_gt24p128g_s5kjns_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.mot.eeprom.mot_gt24p128g_s5kjns_eeprom.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.mot.eeprom.mot_gt24p128g_s5kjns_uw_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.mot.eeprom.mot_gt24p128g_s5kjns_uw_eeprom.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.qti.sensor.mot_s5kgnj.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.mot_s5kgnj.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.qti.sensor.mot_s5kjns.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.mot_s5kjns.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.qti.sensor.mot_s5kjns_uw.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensor.mot_s5kjns_uw.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_roadstr_s5kgnj_qtech.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_roadstr_s5kgnj_qtech.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_roadstr_s5kjns_ofilm.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_roadstr_s5kjns_ofilm.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_roadstr_s5kjns_uw_sunny.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_roadstr_s5kjns_uw_sunny.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.qti.tuned.mot_roadstr_s5kgnj.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_roadstr_s5kgnj.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.qti.tuned.mot_roadstr_s5kjns.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_roadstr_s5kjns.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/com.qti.tuned.mot_roadstr_s5kjns_uw.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_roadstr_s5kjns_uw.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/components/com.arcsoft.node.dc_capture.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/components/com.arcsoft.node.dc_capture.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/components/com.arcsoft.node.dc_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/components/com.arcsoft.node.dc_preview.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/components/com.vidhance.node.gme.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/components/com.vidhance.node.gme.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/components/com.vidhance.node.preview.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/components/com.vidhance.node.preview.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/components/com.vidhance.node.processing.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/components/com.vidhance.node.processing.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/components/com.vidhance.node.video.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/components/com.vidhance.node.video.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/components/com.vidhance.node.zoom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/components/com.vidhance.node.zoom.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigoffline.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigoffline.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigpreview.mot_s5kgnj.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.mot_s5kgnj.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigpreview.mot_s5kjns.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.mot_s5kjns.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigpreview.mot_s5kjns_uw.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.mot_s5kjns_uw.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigsecure.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigsecure.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigvideo.mot_s5kgnj.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.mot_s5kgnj.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigvideo.mot_s5kjns.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.mot_s5kjns.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigvideo.mot_s5kjns_uw.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.mot_s5kjns_uw.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/motorola/roadstr/proprietary/vendor/lib64/com.motorola.hardware.biometric.fingerprint-V2-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.motorola.hardware.biometric.fingerprint-V2-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/com.motorola.hardware.display.config-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.motorola.hardware.display.config-V1-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/com.motorola.hardware.display.panel-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.motorola.hardware.display.panel-V1-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/com.motorola.hardware.display.panel-V2-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.motorola.hardware.display.panel-V2-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/com.motorola.hardware.display.panel@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.motorola.hardware.display.panel@1.0.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/com.motorola.hardware.display.touch-V3-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.motorola.hardware.display.touch-V3-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/com.motorola.hardware.ifaa-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/com.motorola.hardware.ifaa-V1-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/hw/fingerprint.goodix.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.goodix.default.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_chi_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_chi_utils.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_distortion_correction.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_distortion_correction.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_portrait_distortion_correction.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_portrait_distortion_correction.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_qnnhtp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_qnnhtp.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_tf_portrait_distortion_correction.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_tf_portrait_distortion_correction.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_tfs_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_tfs_hdr.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_tfs_motioncapture.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_tfs_motioncapture.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_tfs_portrait_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_tfs_portrait_hdr.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_tfs_portrait_sn.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_tfs_portrait_sn.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_tfs_sn.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_tfs_sn.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoft_tfs_sr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_tfs_sr.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libarcsoftpostprocservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoftpostprocservice.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libcodec2_store_dolby.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcodec2_store_dolby.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libmot_afd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmot_afd.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libmot_engine_settings.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmot_engine_settings.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/libvidhance.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvidhance.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.fdr-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.fdr-V1-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.haptic-V2-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.haptic-V2-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.health.aidl-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.health.aidl-V1-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.health.storage.aidl-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.health.storage.aidl-V1-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.health.storage@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.health.storage@1.0.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.lpsensing-V1-ndk_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.lpsensing-V1-ndk_platform.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.power-V1-ndk_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.power-V1-ndk_platform.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.power-V2-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.power-V2-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.rpmb-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.rpmb-V1-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.sensors-V1-ndk_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.sensors-V1-ndk_platform.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.sxf-V2-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.sxf-V2-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.tcmdaidl-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.tcmdaidl-V1-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/motorola.hardware.wireless.wlc-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/motorola.hardware.wireless.wlc-V1-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/nfc_nci.st21nfc.st.so:$(TARGET_COPY_OUT_VENDOR)/lib64/nfc_nci.st21nfc.st.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/vendor.dolby.dms-V1-ndk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.dolby.dms-V1-ndk.so \
    vendor/motorola/roadstr/proprietary/vendor/lib64/vendor.dolby.hardware.dms@2.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/vendor.dolby.hardware.dms@2.0.so \
    vendor/motorola/roadstr/proprietary/vendor/usr/keylayout/goodix_ts.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/goodix_ts.kl \
    vendor/motorola/roadstr/proprietary/system_ext/bin/hw/motorola.hardware.tcmd@1.0-service:$(TARGET_COPY_OUT_SYSTEM_EXT)/bin/hw/motorola.hardware.tcmd@1.0-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/android.hardware.biometrics.face-service.face-isv:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.biometrics.face-service.face-isv \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/android.hardware.biometrics.fingerprint-service-jv:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.biometrics.fingerprint-service-jv \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/com.motorola.hardware.display.panel-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/com.motorola.hardware.display.panel-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/com.motorola.hardware.display.touch-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/com.motorola.hardware.display.touch-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/com.motorola.hardware.ifaa-V1-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/com.motorola.hardware.ifaa-V1-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/motorola.hardware.fdr-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.fdr-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/motorola.hardware.haptic-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.haptic-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/motorola.hardware.health-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.health-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/motorola.hardware.health.storage-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.health.storage-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/motorola.hardware.health.storage@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.health.storage@1.0-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/motorola.hardware.lpsensing-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.lpsensing-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/motorola.hardware.power-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.power-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/motorola.hardware.rpmb-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.rpmb-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/motorola.hardware.sensorext-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.sensorext-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/motorola.hardware.wireless.wlc-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/motorola.hardware.wireless.wlc-service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/vendor.dolby.dms.service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.dolby.dms.service \
    vendor/motorola/roadstr/proprietary/vendor/bin/hw/vendor.dolby.media.c2-default-service-dax:$(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.dolby.media.c2-default-service-dax

PRODUCT_PACKAGES += \
    com.motorola.hardware.camera.desktop \
    com.motorola.hardware.display.panel-service.xml \
    motorola.hardware.fdr.service.xml \
    motorola.hardware.haptic.xml \
    motorola.hardware.health.service.xml \
    motorola.hardware.health.storage.service.xml \
    motorola.hardware.lpsensing.service.xml \
    motorola.hardware.power.service.xml \
    motorola.hardware.sensorext.service.xml \
    motorola.hardware.wireless.wlc.xml \
    vendor.dolby.media.c2-default-service-dax.xml \
    vendor.motorola.hardware.sxf.service.xml \
    motorola.hardware.tcmd@1.0-service.xml \
    motorola.hardware.tcmdaidl-service.xml \
